/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRoute,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/tours': typeof ToursRouteWithChildren
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours': typeof ToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/tours': typeof ToursRouteWithChildren
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/tours' | '/tours/$slug' | '/tours/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/tours/$slug' | '/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/tours'
    | '/tours/$slug'
    | '/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ToursRoute: typeof ToursRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRoute
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
  }
}

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ToursRoute: ToursRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
